### ISSUE TITLE
Apparently chinese translation of this mod is wrong

### ISSUE THREAD

**Issue by dydzio0614** [vcmi-mods/retreat-town#10]
Heroes skills descriptions apparently do not match what they do. Reported by user to me on... Steam :P

**Comment by Fabrice-TIERCELIN** [comment]
@by003, have you noticed such issues?

**Comment by by003** [comment]
Actually Retreat town was not my work. If I am free I will check it.

**Comment by by003** [comment]
I really don't like the design of retreat town even if I am from China, so I have no plan for remake it as well.
